services:
  postgres:
    image: postgres:15-alpine
#    volumes:
#      - ./postgresql-database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app

networks:
  app:
