name: NestJS Boilerplate
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run lint
      - run: npm run build
      - run: npm run test

